const fs = require("fs");
const path = require("path");

const targetPath = path.join(
  __dirname,
  "src",
  "environments",
  "environment.ts",
);
const dirPath = path.dirname(targetPath);

if (!fs.existsSync(dirPath)) {
  fs.mkdirSync(dirPath, { recursive: true });
}

// Fallback to localhost for local development if no BACKEND_URL is specified
const backendUrl = process.env.BACKEND_URL || "http://localhost:8080";

const envConfigFile = `// This file is auto-generated by set-env.js
export const environment = {
  production: ${process.env.NODE_ENV === "production" ? "true" : "false"},
  apiUrl: '${backendUrl.replace(/\/$/, "")}'
};
`;

fs.writeFileSync(targetPath, envConfigFile, "utf8");
console.log(`Angular environment.ts generated with apiUrl: ${backendUrl}`);
