name: Pull Request Tests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Zulu)
        uses: actions/setup-java@v4
        with:
          java-version: "21" # Versión de Java
          distribution: "zulu"
          cache: maven

      - name: Validate Maven Wrapper
        run: chmod a+x Maki/mvnw

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: angular/package-lock.json

      - name: Install Angular dependencies
        run: npm install --no-audit --no-fund --quiet
        working-directory: angular

      - name: Start Angular app
        run: npm start -- --watch=false &
        working-directory: angular

      - name: Wait for Angular to be ready
        run: npx wait-on http://localhost:4200 --timeout 120000

      - name: Run Maven tests
        run: ./mvnw test
        working-directory: Maki
        env:
          SPRING_PROFILES_ACTIVE: test

      # Reportar los resultados de los tests en el PR
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: Maki/target/surefire-reports/
